### ISSUE TITLE
Demo video for 1st of June

### ISSUE THREAD

**Issue by lrollet1** [SDP-Rock-Paper-Scissors/RockPaperScissors#113]

**Comment by panadax** [comment]
https://user-images.githubusercontent.com/33196494/170365890-74cf16b4-beea-482c-819c-6071051a6d73.mp4


Just the first, rough demo video, content needs to be decided... Please have a quick check :)

**Comment by gaetschwartz** [comment]
@panadax I really like the idea !

**Comment by panadax** [comment]
https://user-images.githubusercontent.com/33196494/171296161-9a9fb5f6-d4fa-4187-882b-734518c5406c.mp4

Updated according to the latest UI design.
