### ISSUE TITLE
Make sure cache tests have proper names @leonardopennino

### ISSUE THREAD

**Issue by gaetschwartz** [SDP-Rock-Paper-Scissors/RockPaperScissors#137]

**Comment by leonardopennino** [comment]
I think cache tests name are already ok, if you think otherwise please reopen this issue and tell me what you think should be changed.
[Cache.kt](https://github.com/SDP-Rock-Paper-Scissors/RockPaperScissors/blob/main/app/src/main/java/ch/epfl/sweng/rps/persistence/Cache.kt)
