### ISSUE TITLE
When the scissors is selected by a computer, the user's scissors button is highlighted instead.

### ISSUE THREAD

**Issue by gaetschwartz** [SDP-Rock-Paper-Scissors/RockPaperScissors#97]
https://user-images.githubusercontent.com/25441359/166140966-85c09219-6647-4856-a8c6-b58ad1a24dce.mov

**Comment by adam-narozniak** [comment]
Please check if you're not up to date with the branch. I also saw this issue some time ago and fixed it.
https://github.com/SDP-Rock-Paper-Scissors/RockPaperScissors/blob/b18251aa23bc50eba89dba45396f8e2b1a5a7254/app/src/main/java/ch/epfl/sweng/rps/ui/game/GameFragment.kt#L81-L93
It was line 90 that didn't have the postfix "opponent" in the name when I was writing it for the first time.
